mash-up-kr/TwoToo_Android

presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/theme/Font.kt
close #36 
- 폰트 타이포그라피 추가했어요~!
=> [feat] 타이포그라피 추가

presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/textfield/TextField.kt
close #29 
- 공통 TextField를 제작하였습니다. 
|기능|스크린샷|
|:---|---|
|TextField제작|<img width="420" alt="스크린샷 2023-06-04 오후 4 17 55" src="https://github.com/mash-up-kr/TwoToo_Android/assets/62296097/61afff4d-0451-4c39-bb52-ea960627ea96">
|
=> [feat]: create textfield

presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/ImageView.kt, presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/Navigation.kt, presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/bottomsheet/Authenticate.kt, presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/bottomsheet/Header.kt, presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/button/TwoTooIconButton.kt, presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/dialog/TwoTooDialog.kt, presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/textfield/TextField.kt
- 미적용된 공통 컴포넌트 디자인 시스템 적용
- 카카오 로그인 text는 figma 바뀌면 수정해야할 것 같아요!
=> 공통 컴포넌트 디자인 시스템 적용

presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/ImageView.kt
close #50 
- ContentScale parameter를 추가했습니다.
- default로는 ContentScale.Crop를 적용합니다.
x
=> TwoTooImageView ContentScale parameter추가

gradle/libs.versions.toml, presenter/build.gradle.kts
=> Test용 Dependency추가

presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/theme/Color.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/before/HomeBeforeChallenge.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/components/HomeGoalCount.kt
x
- HomeGoalCount에 count visiblity를 추가했어요
=> BeforeChallenge에 challenge count visibility추가

presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/bottomsheet/Authenticate.kt, presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/textfield/TextField.kt, presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/theme/Font.kt
close #118 
2줄 이상되는 곳이 16사이즈 폰트만 있는 것 같아서 거기에만 적용합니다
=> 16사이트 폰트에 line height지정

presenter/src/main/java/com/mashup/twotoo/presenter/garden/Garden.kt, presenter/src/main/java/com/mashup/twotoo/presenter/garden/GardenState.kt, presenter/src/main/java/com/mashup/twotoo/presenter/garden/GardenViewModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/history/HistoryScreen.kt, presenter/src/main/java/com/mashup/twotoo/presenter/history/HistoryState.kt, presenter/src/main/java/com/mashup/twotoo/presenter/history/HistoryViewModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/history/datail/HistoryDetailScreen.kt, presenter/src/main/java/com/mashup/twotoo/presenter/history/datail/HistoryDetailState.kt, presenter/src/main/java/com/mashup/twotoo/presenter/history/datail/HistoryDetailViewModel.kt
close #100 
- history mvi 적용
- garden mvi 적용
history detail이랑 history 랑 같은 state, viewModel 사용하려다가 분리했는데, 보통 viewModel을 여러 screen에서 같이 사용하기도 하나용? 저는 histroy list 가져오는 api call 한번으로 history detail 데이터도 얻어올 수 있을것 같아서 같이 사용해도 될거라고 생각했어요.  서버 나오는 거에 따라 다를거 같긴한데 의견주시면 감사하겠습니다. 
ui 변한게없어용 ㅜ
=> 히스토리, 정원 mvi 적용

presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/auth/both/HomeOngoingBothAuthTest.kt, presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/auth/doNotBoth/HomeOngoingDoNotAuthBothTest.kt, presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/auth/firstCreateChallenge/HomeOngoingFirstChallengeTest.kt, presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/auth/onlyMe/HomeOngoingAuthOnlyMeTest.kt, presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/auth/onlyPartner/HomeOngoingAuthOnlyPartnerTest.kt, presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/cheer/both/HomeCheerBothTest.kt, presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/cheer/doNotBoth/HomeCheerDoNotBothTest.kt, presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/cheer/onlyMe/HomeCheerOnlyMeTest.kt, presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/cheer/onlyPartner/HomeCheerOnlyPartner.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/Home.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/HomeViewModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/mapper/HomeViewMapper.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/model/AuthType.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/model/ChallengeStateTypeUiModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/model/HomeCheerUiModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/model/HomeFlowerUiModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/model/flower/Flower.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/components/HomeFlower.kt, presenter/src/test/java/com/mashup/twotoo/presenter/home/HomeViewModelTest.kt
x
- 각 데이터 모델별로 state를 가지는 format으로 통일성을 유지하도록 하였습니다
- 기존의 최상단의 sealed interface를 data class로 대체하였습니다.
- UiModel test코드에 반영했습니다.
=> UiModel Refactor

presenter/src/test/java/com/mashup/twotoo/presenter/home/repository/FakeChallengeRepository.kt
=> [hotfix] : return type

presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/auth/firstCreateChallenge/HomeOngoingFirstChallengeTest.kt, presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/auth/onlyPartner/HomeOngoingAuthOnlyPartnerTest.kt, presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/toast/TwoTooSnackbar.kt, presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/theme/Color.kt
x
- 토스트 배경 & 글자 색 변경
|기능|스크린샷|
|:---|---|
|기능B 구현||
|...||
=> [fix] : change toast background & text color

data/src/main/java/com/mashup/twotoo/datasource/remote/user/response/UserInfoResponse.kt, data/src/main/java/com/mashup/twotoo/mapper/UserMapper.kt, domain/src/main/java/model/user/UserInfoDomainModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/toolbar/TwoTooBackToolbar.kt, presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/toolbar/TwoTooMainToolbar.kt, presenter/src/main/java/com/mashup/twotoo/presenter/garden/Garden.kt, presenter/src/main/java/com/mashup/twotoo/presenter/history/HistoryScreen.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/model/HomeGoalCountUiModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/mypage/MyPage.kt, presenter/src/main/java/com/mashup/twotoo/presenter/mypage/UserState.kt, presenter/src/main/java/com/mashup/twotoo/presenter/mypage/UserViewModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/mypage/di/UserComponent.kt, presenter/src/main/java/com/mashup/twotoo/presenter/mypage/di/UserModule.kt, presenter/src/main/java/com/mashup/twotoo/presenter/mypage/navigation/UserNavigation.kt
close #131 
- my page ui 수정
-  api 연결
- 빌드 확인해보니 toolbar size 작아져서 text가 잘려가지궁 적당하게 바꿔봤어요
=> 마이페이지 api 연결

presenter/src/main/java/com/mashup/twotoo/presenter/invite/WaitingAcceptPair.kt, presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/OnBoardingViewModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/util/KaKaoAuthFlow.kt
- 카카오 유저 정보 가져오는 부분 타이밍 이슈로 못가져오는 경우가 있어서 
확실하게 성공하고 받아올 수 있도록 수정했습니다~!
- Continuation 이용해서 카카오 sdk안에 있는 userModel를 반환할 수 있더라구요!
=> Refactor login

data/src/main/java/com/mashup/twotoo/datasource/remote/user/response/UserInfoResponse.kt, domain/src/main/java/model/user/UserInfoDomainModel.kt
=> [fix] userInfo partnerInfo nullable

presenter/src/main/java/com/mashup/twotoo/presenter/ui/TwoTooAppState.kt
x
네비게이션 수정
|기능|스크린샷|
|:---|---|
|기능B 구현||
|...||
=> [fix] : remove findStartDestination

presenter/src/main/java/com/mashup/twotoo/presenter/history/HistoryComponents.kt, presenter/src/main/java/com/mashup/twotoo/presenter/history/HistoryScreen.kt, presenter/src/main/java/com/mashup/twotoo/presenter/history/HistoryViewModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/history/di/HistoryModule.kt, presenter/src/main/java/com/mashup/twotoo/presenter/history/model/ChallengeInfoUiModel.kt
close #1
history 인증하기 연결
history 인증하기 연결
=> fix: history 인증하기 버튼 bottomsheet과 연결

presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/progressbar/TwoTooGoalAchievementProgressbar.kt, presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/toolbar/TwoTooMainToolbar.kt, presenter/src/main/java/com/mashup/twotoo/presenter/garden/Garden.kt, presenter/src/main/java/com/mashup/twotoo/presenter/history/HistoryScreen.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/Home.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/mapper/HomeViewMapper.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/HomeOngoingChallenge.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/components/HomeGoalCount.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/components/HomeGoalField.kt, presenter/src/main/java/com/mashup/twotoo/presenter/mypage/MyPage.kt, presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/OnBoarding.kt, presenter/src/main/java/com/mashup/twotoo/presenter/ui/TwoTooApp.kt, presenter/src/main/java/com/mashup/twotoo/presenter/util/AutoSizeText.kt
상단바 패딩 적용, 텍스트 짤리는거 수정, 홈 맵퍼 수정
=> Refactor/home UI

presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/bottomsheet/Authenticate.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/components/HomeFlower.kt, presenter/src/main/java/com/mashup/twotoo/presenter/invite/WaitingAcceptPair.kt, presenter/src/main/java/com/mashup/twotoo/presenter/nickname/NickNameSetting.kt, presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/navigation/OnBoardingNavigation.kt, presenter/src/main/java/com/mashup/twotoo/presenter/util/FirebaseDeepLink.kt
- UI 버그 수정 2차 
- 닉네임 잘못된 링크 토스트 메세지 노출 수정 
- 인증하기 UI 깨지는 이슈 등등
=> UI 버그 수정 2차

presenter/src/main/java/com/mashup/twotoo/presenter/garden/Garden.kt, presenter/src/main/res/values/string.xml
close #1
feat: history ui 변경된것 수정
=> feat: history ui 변경된것 수정

app/src/main/java/com/mashup/twotoo/TwotooFirebaseMessagingService.kt, presenter/src/main/java/com/mashup/twotoo/presenter/createChallenge/CreateChallenge.kt, presenter/src/main/java/com/mashup/twotoo/presenter/createChallenge/model/RecommendChallengeUiModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/createChallenge/selectflower/SelectFlowerCard.kt, presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/dialog/TwoTooDialog.kt, presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/textfield/TextField.kt, presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/theme/Font.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/HomeViewModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/before/HomeBeforeChallenge.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/HomeOngoingChallenge.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/components/HomeFlower.kt, presenter/src/main/java/com/mashup/twotoo/presenter/invite/SendInvitation.kt, presenter/src/main/java/com/mashup/twotoo/presenter/invite/WaitingAcceptPair.kt, presenter/src/main/java/com/mashup/twotoo/presenter/nickname/NickNameSetting.kt, presenter/src/main/res/values/string.xml
=> Notification Push

presenter/src/main/java/com/mashup/twotoo/presenter/history/HistoryViewModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/history/di/HistoryModule.kt
close #1
fix: user list userNo체크
|기능|스크린샷|
|:---|---|
|기능B 구현||
|...||
=> fix: user list userNo체크

presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/components/HomeFlower.kt
=> [fix] : logic

presenter/src/main/java/com/mashup/twotoo/presenter/guid/GuideWebView.kt, presenter/src/main/java/com/mashup/twotoo/presenter/mypage/model/MyPageItem.kt
close #1
feat: webview toolbar text 변경
=> feat: webview toolbar text 변경

presenter/src/main/res/values/string.xml
=> [fix] : string resource

presenter/src/main/java/com/mashup/twotoo/presenter/createChallenge/CreateChallengeOneStep.kt, presenter/src/main/java/com/mashup/twotoo/presenter/createChallenge/model/RecommendChallengeUiModel.kt
close #1
feat: 챌린지 저장시 icon 자르기
=> feat: 챌린지 저장시 icon 자르기

presenter/src/main/java/com/mashup/twotoo/presenter/history/HistoryScreen.kt, presenter/src/main/java/com/mashup/twotoo/presenter/history/model/ChallengeInfoUiModel.kt
close #1
fix: 완료된 챌린지만 챌린지 그만두게 수정
|기능|스크린샷|
|:---|---|
|기능B 구현||
|...||
=> fix: 완료된 챌린지만 챌린지 그만두게 수정

presenter/src/main/java/com/mashup/twotoo/presenter/history/HistoryScreen.kt, presenter/src/main/java/com/mashup/twotoo/presenter/history/navigation/HistoryNavigation.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/Home.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/HomeSideEffectHandler.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/HomeViewModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/model/HomeSideEffect.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/navigation/HomeNavigation.kt
close #1
feat: history에 progressbar 데이터 연결
|기능|스크린샷|
|:---|---|
|기능B 구현||
|...||
=> feat: history에 progressbar 데이터 연결

presenter/src/main/java/com/mashup/twotoo/presenter/history/HistoryViewModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/history/model/ChallengeInfoUiModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/history/model/HistoryItemUiModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/util/DateFormatter.kt
close #1
fix: 미인증 이슈 해결
|기능|스크린샷|
|:---|---|
|기능B 구현||
|...||
=> fix: 미인증 이슈 해결

.gitignore, app/src/main/AndroidManifest.xml, data/src/main/java/com/mashup/twotoo/di/NetworkModule.kt
close #1
- DI
- Base Activity, Base Fragment
- 라이브러리 세팅
- 바텀 네비게이션 세팅
- 기타 뷰 세팅
|기능|스크린샷|
|:---|---|
|기능B 구현||
|...||
=> [feat] : update

.github/workflows/blank.yml, .gitignore, app/build.gradle.kts, app/proguard-rules.pro
=> [chore] : release setting

app/build.gradle.kts
=> [chore]: update version

presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/bottomsheet/BottomSheet.kt, presenter/src/main/res/values/string.xml
x
- 권한 토스트 텍스트를 변경하였습니다.
- 권한 토스트의 경우에는 시스템 토스트를 사용합니다.
x
=> 권한 토스트 텍스트 변경

presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/dialog/TwoTooDialog.kt, presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/toolbar/TwoTooMainToolbar.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/Home.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/mapper/HomeViewMapper.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/model/Flower.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/model/HomeCheerUiModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/HomeOngoingChallenge.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/components/HomeFlower.kt, presenter/src/main/java/com/mashup/twotoo/presenter/home/preview/parameter/PreviewOngoingCheerHomeParameterProvider.kt, presenter/src/main/java/com/mashup/twotoo/presenter/util/DevicePreview.kt
x
- HomeViewMapper 4단계 5단계 수정
- 앱바 TopAppBar - > Row로 수정
- 다이얼로그 힌트 적용
|기능|스크린샷|
|:---|---|
|다이얼로그 힌트  적용|<img width="329" alt="스크린샷 2023-08-05 오후 6 34 25" src="https://github.com/mash-up-kr/TwoToo_Android/assets/62296097/54bdea47-41ee-46e6-b5da-2247f56a90a0">|
|...||
=> 4단계,5단계 맵핑 수정 및 앱바 수정 & 다이얼로그 힌트 수정

presenter/src/main/AndroidManifest.xml, presenter/src/main/java/com/mashup/twotoo/presenter/createChallenge/CreateChallenge.kt, presenter/src/main/java/com/mashup/twotoo/presenter/createChallenge/selectflower/FlowerCardItem.kt, presenter/src/main/java/com/mashup/twotoo/presenter/guid/GuideWebView.kt, presenter/src/main/java/com/mashup/twotoo/presenter/history/model/ChallengeInfoUiModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/invite/SendInvitation.kt, presenter/src/main/java/com/mashup/twotoo/presenter/invite/WaitingAcceptPair.kt, presenter/src/main/java/com/mashup/twotoo/presenter/nickname/NickNameSetting.kt, presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/OnBoarding.kt, presenter/src/main/java/com/mashup/twotoo/presenter/util/DateFormatter.kt
- 웹뷰 스크롤 잘리는 현상 수정
- 인증하기 디데이 홈화면과 다른 이슈
- 온보딩 카카오 로그인 버튼 잘리는 이슈
- 챌린지 수락 시 스택 남아있는 이슈 + 딥링크 시 앱 두번 실행 되는 이슈 -> 테스트 필요
- 꽃 선택 설명 글씨 가운데 정렬
=> 짜잘한 UI 및 기능 수정

app/build.gradle.kts
=> [fix] : update version

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/com/mashup/twotoo/TwotooFirebaseMessagingService.kt, presenter/src/main/res/values/string.xml
=> [fix] : head up notification

presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/components/HomeGoalCount.kt
close #1
- DI
- Base Activity, Base Fragment
- 라이브러리 세팅
- 바텀 네비게이션 세팅
- 기타 뷰 세팅
|기능|스크린샷|
|:---|---|
|기능B 구현||
|...||
=> [fix] 마이페이지 닉네임 width 수정

presenter/src/main/res/values/string.xml
close #240 
"00가 보낸 칭찬" 에서 "00의 칭찬 한마디" 로 변경
|기능|스크린샷|
|:---|---|
|이전 텍스트|![KakaoTalk_Photo_2023-08-18-13-29-40](https://github.com/mash-up-kr/TwoToo_Android/assets/62296097/19ef00a7-a11a-4a4e-9575-3dd27679a01f)|
|바꾼 텍스트|![KakaoTalk_Photo_2023-08-18-13-29-37](https://github.com/mash-up-kr/TwoToo_Android/assets/62296097/eae87133-d02b-4be3-871d-d135976af0e3)|
=> [fix] : 칭찬 문구 수정

presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/bottomsheet/ShotAndCheer.kt, presenter/src/main/res/values/string.xml
close #235 
- 칭찬하기와 찌르기의 글자수를 20자로 제한합니다.
|기능|스크린샷|
|:---|---|
|글자수 제한 |Uploading KakaoTalk_Video_2023-08-18-15-51-45.mp4…|
=> [fix] : 글자수 20자 제한

presenter/src/main/java/com/mashup/twotoo/presenter/home/Home.kt, presenter/src/main/java/com/mashup/twotoo/presenter/util/Debounce.kt
close #236 
- coroutine으로 debounce 로직을 추가했습니다
- onClick Event로 viewModel 함수를 호출하는 코드에서 debounce를 걸어주었어요
|기능|스크린샷|
|:---|---|
|디바운스 적용 위치|<img width="1092" alt="스크린샷 2023-08-24 오후 2 24 24" src="https://github.com/mash-up-kr/TwoToo_Android/assets/62296097/cfc5b4de-0e8e-4095-9f5a-ce0cebae0675">|
|디바운스 로그|<img width="1092" alt="스크린샷 2023-08-24 오후 2 23 30" src="https://github.com/mash-up-kr/TwoToo_Android/assets/62296097/183463db-2938-41b6-8c67-90d08faabec0">|
=> [feat] : add debonce util and apply

data/src/main/java/com/mashup/twotoo/datasource/remote/challenge/ChallengeApi.kt, data/src/main/java/com/mashup/twotoo/datasource/remote/challenge/ChallengeDataSource.kt, data/src/main/java/com/mashup/twotoo/datasource/remote/challenge/response/Challenge.kt, data/src/main/java/com/mashup/twotoo/di/NetworkModule.kt, data/src/main/java/com/mashup/twotoo/mapper/ChallengeMapper.kt, data/src/main/java/com/mashup/twotoo/repository/ChallengeRepositoryImpl.kt, domain/src/main/java/model/challenge/response/HistoryChallengeDomainModel.kt, domain/src/main/java/repository/ChallengeRepository.kt, domain/src/main/java/usecase/challenge/GetChallengeHistoriesUseCase.kt, presenter/src/main/java/com/mashup/twotoo/presenter/garden/Garden.kt, presenter/src/main/java/com/mashup/twotoo/presenter/garden/GardenComponents.kt, presenter/src/main/java/com/mashup/twotoo/presenter/garden/GardenViewModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/garden/di/GardenModule.kt, presenter/src/main/java/com/mashup/twotoo/presenter/garden/mapper/GardenMapper.kt, presenter/src/main/java/com/mashup/twotoo/presenter/garden/model/ChallengeCardInfoUiModel.kt, presenter/src/main/res/values/string.xml
|기능|스크린샷|
|:---|---|
|기능B 구현||
|...||
=> 진행중인 히스토리가 보이도록 수정합니다.

presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/components/HomeGoalField.kt, presenter/src/main/res/drawable/ic_arrow.xml
close #259 
x
x
|기능|스크린샷|
|:---|---|
|화살표 추가|<img width="364" alt="스크린샷 2023-09-21 오후 9 37 47" src="https://github.com/mash-up-kr/TwoToo_Android/assets/62296097/bd0198d3-5746-4303-bec1-8386560e28ac">|
=> 메인 화면 title에 화살표 이미지 추가

data/src/main/java/com/mashup/twotoo/di/NetworkModule.kt, presenter/src/main/java/com/mashup/twotoo/presenter/history/HistoryComponents.kt, presenter/src/main/java/com/mashup/twotoo/presenter/history/HistoryViewModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/invite/InviteViewModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/mypage/MyPage.kt, presenter/src/main/java/com/mashup/twotoo/presenter/mypage/UserSideEffect.kt, presenter/src/main/java/com/mashup/twotoo/presenter/mypage/UserViewModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/mypage/navigation/UserNavigation.kt, presenter/src/main/java/com/mashup/twotoo/presenter/nickname/NickNameSetting.kt, presenter/src/main/java/com/mashup/twotoo/presenter/nickname/NickNameViewModel.kt, presenter/src/main/java/com/mashup/twotoo/presenter/nickname/navigation/NickNameSettingNavigation.kt, presenter/src/main/java/com/mashup/twotoo/presenter/splash/navigation/SplashNavigation.kt, presenter/src/main/res/values/string.xml
- 닉네임 변경 툴바, 버튼 텍스트, 토스트 띄우기 추가
- 히스토리 목록 endDate 안맞을 때 수정
- 히스토리 목록 디데이 수정
|기능|스크린샷|
|:---|---|
|기능B 구현||
|...||
=> 닉네임 변경 수정 및 히스토리 목록 수정

app/build.gradle.kts
close #1
- DI
- Base Activity, Base Fragment
- 라이브러리 세팅
- 바텀 네비게이션 세팅
- 기타 뷰 세팅
|기능|스크린샷|
|:---|---|
|기능B 구현||
|...||
=> [fix] version

presenter/src/main/java/com/mashup/twotoo/presenter/createChallenge/selectflower/FlowerCardItem.kt, presenter/src/main/java/com/mashup/twotoo/presenter/invite/WaitingAcceptPair.kt, presenter/src/main/java/com/mashup/twotoo/presenter/invite/navigation/InviteNavigation.kt, presenter/src/main/res/values/string.xml
close #1
- 수락 초대페이지 나가기 버튼 생성
- 챌린지 꽃선택 꽃말 잘리는 이슈 수정(autosize)
|기능|스크린샷|
|:---|---|
|기능B 구현||
|...||
=> 수락 초대 페이지 나가기 버튼 생성
